### ISSUE TITLE
Cancel is not working

### ISSUE THREAD

**Issue by artemShelest** [cardknox/cardknox-sdk-js#96]
Cancel is not working for pending operation.

**Reproduction:**

In public/sample.html make changes:
- add "Cancel" button after "Get signature" button:
```
<button id="signature">Get Signature</button>
<button id="cancel">Cancel</button>
```
- add cancel handler to JS block:
```
        var cancelButton = document.getElementById('cancel');
        cancelButton.addEventListener('click', e => {
            e.preventDefault();

            var config = Object.fromEntries(new FormData(configForm).entries());

            cancel({
                deviceIpAddress: config.deviceIpAddress,
                deviceIpPort: config.deviceIpPort,
                deviceIpProtocol: config.deviceIpProtocol
            }).then(r => {
                if (!r.xError)
                    alert("Operation canceled");
                else
                    alert("Failed to cancel");
            }).catch(console.error);
        });
```
Fill the form.
Click "Submit".
Click "Cancel".

**Expected result:**

POS terminal prompt disappears, alert "Operation canceled" is shown in the browser.

**Actual Result:**

POS terminal prompt remains until timeout, error in the browser console.

**Comment by mstein-ck** [comment]
@artemShelest as per Pax, the 'Cancel' command is not supported in this mode (HTTP/S GET). This command was left in the code base but is not mentioned in the docs.

**Comment by mstein-ck** [comment]
Let me know if you need anything further

**Comment by artemShelest** [comment]
It would be great to explicitly mention in the doc that cancel is not supported.

**Comment by ymwymw** [comment]
@mstein-ck Can we update the docs?

**Comment by ymwymw** [comment]
After further consideration, we felt that the best path forward, would be to remove the cancel functionality.
#97
